Further work on model and initial work on data access object tests

diff --git a/scripts/CreateSpikeStreamDatabases b/scripts/CreateSpikeStreamDatabases
--- a/scripts/CreateSpikeStreamDatabases
+++ b/scripts/CreateSpikeStreamDatabases
@@ -13,27 +13,44 @@
 NETWORK_HOST=localhost
 NETWORK_USER=SpikeStream
 NETWORK_PASSWORD=ekips
+NETWORK_DATABASE=SpikeStreamNetwork
+NETWORK_TEST_DATABASE=SpikeStreamNetworkTest
 
 #----------- SpikeStreamArchive Database -------------
 ARCHIVE_HOST=localhost
 ARCHIVE_USER=SpikeStream
 ARCHIVE_PASSWORD=ekips
+ARCHIVE_DATABASE=SpikeStreamArchive
+ARCHIVE_TEST_DATABASE=SpikeStreamArchiveTest
 
 #----------- SpikeStreamPattern Database -------------------
 PATTERNS_HOST=localhost
 PATTERNS_USER=SpikeStream
 PATTERNS_PASSWORD=ekips
+PATTERNS_DATABASE=SpikeStreamPattern
+PATTERNS_TEST_DATABASE=SpikeStreamPatternTest
 
 #----------- SpikeStreamSimulation Database --------------------
 SIMULATION_HOST=localhost
 SIMULATION_USER=SpikeStream
 SIMULATION_PASSWORD=ekips
+SIMULATION_DATABASE=SpikeStreamSimulation
+SIMULATION_TEST_DATABASE=SpikeStreamSimulationTest
 
 #----------- SpikeStreamDevice Database --------------------
 DEVICES_HOST=localhost
 DEVICES_USER=SpikeStream
 DEVICES_PASSWORD=ekips
+DEVICES_DATABASE=SpikeStreamDevices
+DEVICES_TEST_DATABASE=SpikeStreamDevicesTest
 
+# Double check that user wants to continue - this will erase all databases
+echo "This will erase all of the data in the current databases. Do you want to continue?"
+read confirmResponse
+if [ $confirmResponse != "yes" ]
+then
+  exit 0;
+fi
 
 # Inform user what is going on
 echo ""
@@ -84,70 +101,124 @@ fi
 # Change to directory with sql files
 cd $SPIKESTREAM_ROOT/database
 
+# Delete and recreate all databases
+if ! mysql -h${NETWORK_HOST} -u${NETWORK_USER} -p${NETWORK_PASSWORD} < AddSpikeStreamDatabases.sql
+then
+	echo "Error adding SpikeStream databases."
+	DATABASE_ERROR=true;
+fi
+
 
 # Create the databases
-if ! mysql -h${NETWORK_HOST} -u${NETWORK_USER} -p${NETWORK_PASSWORD} < SpikeStreamNetwork.sql
+if ! mysql ${NETWORK_DATABASE} -h${NETWORK_HOST} -u${NETWORK_USER} -p${NETWORK_PASSWORD} < SpikeStreamNetwork.sql
 then
 	echo "Error creating SpikeStreamNetwork database."
 	DATABASE_ERROR=true;
 fi
+if ! mysql ${NETWORK_TEST_DATABASE} -h${NETWORK_HOST} -u${NETWORK_USER} -p${NETWORK_PASSWORD} < SpikeStreamNetwork.sql
+then
+	echo "Error creating SpikeStreamNetworkTest database."
+	DATABASE_ERROR=true;
+fi
 
-if ! mysql -h${ARCHIVE_HOST} -u${ARCHIVE_USER} -p${ARCHIVE_PASSWORD} < SpikeStreamArchive.sql
+if ! mysql ${ARCHIVE_DATABASE} -h${ARCHIVE_HOST} -u${ARCHIVE_USER} -p${ARCHIVE_PASSWORD} < SpikeStreamArchive.sql
 then 
 	echo "Error creating SpikeStreamArchive database."
 	DATABASE_ERROR=true;
 fi
-
-if ! mysql -h${PATTERNS_HOST} -u${PATTERNS_USER} -p${PATTERNS_PASSWORD} < SpikeStreamPattern.sql
-then
-	echo "Error creating SpikeStreamPattern database."
+if ! mysql ${ARCHIVE_TEST_DATABASE} -h${ARCHIVE_HOST} -u${ARCHIVE_USER} -p${ARCHIVE_PASSWORD} < SpikeStreamArchive.sql
+then 
+	echo "Error creating SpikeStreamArchiveTest database."
 	DATABASE_ERROR=true;
 fi
 
-if ! mysql -h${SIMULATION_HOST} -u${SIMULATION_USER} -p${SIMULATION_PASSWORD} < SpikeStreamSimulation.sql
+#if ! mysql ${PATTERN_DATABASE} -h${PATTERNS_HOST} -u${PATTERNS_USER} -p${PATTERNS_PASSWORD} < SpikeStreamPattern.sql
+#then
+#	echo "Error creating SpikeStreamPattern database."
+#	DATABASE_ERROR=true;
+#fi
+#if ! mysql ${PATTERN_TEST_DATABASE} -h${PATTERNS_HOST} -u${PATTERNS_USER} -p${PATTERNS_PASSWORD} < SpikeStreamPattern.sql
+#then
+#	echo "Error creating SpikeStreamPatternTest database."
+#	DATABASE_ERROR=true;
+#fi
+
+if ! mysql ${SIMULATION_DATABASE} -h${SIMULATION_HOST} -u${SIMULATION_USER} -p${SIMULATION_PASSWORD} < SpikeStreamSimulation.sql
 then
 	echo "Error creating SpikeStreamSimulation database."
 	DATABASE_ERROR=true;
 fi
-
-if ! mysql -h${DEVICES_HOST} -u${DEVICES_USER} -p${DEVICES_PASSWORD} < SpikeStreamDevice.sql
+if ! mysql ${SIMULATION_TEST_DATABASE} -h${SIMULATION_HOST} -u${SIMULATION_USER} -p${SIMULATION_PASSWORD} < SpikeStreamSimulation.sql
 then
-	echo "Error creating SpikeStreamDevice database."
+	echo "Error creating SpikeStreamSimulationTest database."
 	DATABASE_ERROR=true;
 fi
 
+#if ! mysql ${DEVICES_DATABASE} -h${DEVICES_HOST} -u${DEVICES_USER} -p${DEVICES_PASSWORD} < SpikeStreamDevice.sql
+#then
+#	echo "Error creating SpikeStreamDevice database."
+#	DATABASE_ERROR=true;
+#fi
+#if ! mysql ${DEVICES_TEST_DATABASE} -h${DEVICES_HOST} -u${DEVICES_USER} -p${DEVICES_PASSWORD} < SpikeStreamDevice.sql
+#then
+#	echo "Error creating SpikeStreamDeviceTest database."
+#	DATABASE_ERROR=true;
+#fi
+
 
 # Fill databases with any default information.
-if ! mysql -h${NETWORK_HOST} -u${NETWORK_USER} -p${NETWORK_PASSWORD} < AddNeuronTypes.sql
+if ! mysql ${NETWORK_DATABASE} -h${NETWORK_HOST} -u${NETWORK_USER} -p${NETWORK_PASSWORD} < AddNeuronTypes.sql
 then
 	echo "Error adding neuron types."
 	DATABASE_ERROR=true;
 fi
+if ! mysql ${NETWORK_TEST_DATABASE} -h${NETWORK_HOST} -u${NETWORK_USER} -p${NETWORK_PASSWORD} < AddNeuronTypes.sql
+then
+	echo "Error adding neuron types to test database."
+	DATABASE_ERROR=true;
+fi
 
-if ! mysql -h${NETWORK_HOST} -u${NETWORK_USER} -p${NETWORK_PASSWORD} < AddSynapseTypes.sql
+if ! mysql ${NETWORK_DATABASE} -h${NETWORK_HOST} -u${NETWORK_USER} -p${NETWORK_PASSWORD} < AddSynapseTypes.sql
 then
 	echo "Error adding synapse types."
 	DATABASE_ERROR=true;
 fi
-
-if ! mysql -h${NETWORK_HOST} -u${NETWORK_USER} -p${NETWORK_PASSWORD} < AddPatternTypes.sql
+if ! mysql ${NETWORK_TEST_DATABASE} -h${NETWORK_HOST} -u${NETWORK_USER} -p${NETWORK_PASSWORD} < AddSynapseTypes.sql
 then
-	echo "Error adding pattern types."
+	echo "Error adding synapse types to test database."
 	DATABASE_ERROR=true;
 fi
 
-if ! mysql -h${DEVICES_HOST} -u${DEVICES_USER} -p${DEVICES_PASSWORD} < AddDevices.sql
-then
-	echo "Error adding device types."
-	DATABASE_ERROR=true;
-fi
+#if ! mysql ${PATTERN_DATABASE} -h${PATTERN_HOST} -u${PATTERN_USER} -p${PATTERN_PASSWORD} < AddPatternTypes.sql
+#then
+#	echo "Error adding pattern types."
+#	DATABASE_ERROR=true;
+#fi
+#if ! mysql ${PATTERN_TEST_DATABASE} -h${PATTERN_HOST} -u${PATTERN_USER} -p${PATTERN_PASSWORD} < AddPatternTypes.sql
+#then
+#	echo "Error adding pattern types to test database."
+#	DATABASE_ERROR=true;
+#fi
+
+#if ! mysql ${DEVICES_DATABASE} -h${DEVICES_HOST} -u${DEVICES_USER} -p${DEVICES_PASSWORD} < AddDevices.sql
+#then
+#	echo "Error adding device types."
+#	DATABASE_ERROR=true;
+#fi
+#if ! mysql ${DEVICES_TEST_DATABASE} -h${DEVICES_HOST} -u${DEVICES_USER} -p${DEVICES_PASSWORD} < AddDevices.sql
+#then
+#	echo "Error adding device types to test database."
+#	DATABASE_ERROR=true;
+#fi
 
 
-# Script has finished successfully
-if [ ! $DATABASE_ERROR ]
+# Script has finished with an error
+if [ $DATABASE_ERROR ]
 then
-	echo "Databases successfully created."
+  echo ""
+  exit 1
 fi
+
+echo "Databases successfully created."
 echo ""
-
 
